name = "llm-as-api"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

kv_namespaces = [
{ binding = "KV", id = "f408e682a64b49feb9a5a1dfe6998e8e" }
]

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"